### ISSUE TITLE
安装后启动报错

### ISSUE THREAD

**Issue by PrismAngle** [Le-niao/Yunzai-Bot#1000]
QQ配置完成，正在登录
后续修改账号可以运行命令： npm run login

/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:69
                this.errors.push(new errors.YAMLParseError(pos, code, message));
                                 ^

YAMLParseError: Missing closing 'quote at line 6, column 12:

platform: 1
           ^

    at Composer.onError (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:69:34)
    at _onError (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/resolve-flow-scalar.js:10:42)
    at singleQuotedValue (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/resolve-flow-scalar.js:73:9)
    at Object.resolveFlowScalar (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/resolve-flow-scalar.js:18:21)
    at Object.composeScalar (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/compose-scalar.js:11:29)
    at composeNode (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/compose-node.js:24:34)
    at Object.resolveBlockMap (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/resolve-block-map.js:79:19)
    at Object.composeCollection (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/compose-collection.js:13:36)
    at Object.composeNode (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.composeDoc (/home/yunzai/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/compose-doc.js:32:23) {
  code: 'MISSING_CHAR',
  pos: [ 128, 129 ],
  linePos: [ { line: 6, col: 12 }, { line: 6, col: 13 } ]
}

**Comment by Le-niao** [comment]
检查下配置文件，yaml文件格式错误

**Comment by PrismAngle** [comment]
怎么检查，我是直接git clone过来的

**Comment by PrismAngle** [comment]
> 检查下配置文件，yaml文件格式错误

怎么检查，配置文件在哪一个位置，我只前跑了一个别人打包好的包，今天重新登陆了一下又出现了这个问题。

**Comment by PrismAngle** [comment]
我好像找到一点原因了，我的QQ密码结尾有引号，好像会导致配置文件读取错误，麻烦开发者大大检查一下 @Le-niao
