### ISSUE TITLE
TypeError: cookieUser.getCookie is not a function

### ISSUE THREAD

**Issue by davidelectricfree** [Le-niao/Yunzai-Bot#104]
[2022-04-28T20:09:02.045] [ERROR] error - mysInfo.roleCard
[2022-04-28T20:09:02.046] [ERROR] error - TypeError: cookieUser.getCookie is not a function
    at MysApi.getData (file:///C:/Yunzai-Bot/lib/components/models/MysApi.js:112:31)
    at MysApi.getIndex (file:///C:/Yunzai-Bot/lib/components/models/MysApi.js:259:23)
    at Module.roleCard (file:///C:/Yunzai-Bot/lib/app/mysInfo.js:511:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.dealMsg (file:///C:/Yunzai-Bot/lib/dealMsg.js:179:19)

很奇怪，出现错误，我的ck是按照要求填的啊

**Comment by davidelectricfree** [comment]
莫名其妙自己又好了，奇怪
