### ISSUE TITLE
角色攻略报错

### ISSUE THREAD

**Issue by JalonShaw** [Le-niao/Yunzai-Bot#1092]
今天设置了一下角色攻略（#设置默认攻略2，4个都试了），然后就一直报错，怎么解决呢

[YzBot][22:51:31.934][INFO] recv from: [Private: 759142587(friend)] #钟离攻略
[YzBot][22:51:32.227][MARK] [米游社攻略][strategy][私聊][ときさき くるみ(759142587)] #钟离攻略
[YzBot][22:51:32.229][ERRO] [米游社攻略][strategy]
[YzBot][22:51:32.230][ERRO] TypeError: Cannot read properties of undefined (reading 'forEach')
    at strategy.getImg (file:///C:/Users/Administrator/Desktop/Yunzai-Bot/plugins/genshin/apps/strategy.js:143:31)
    at strategy (file:///C:/Users/Administrator/Desktop/Yunzai-Bot/plugins/genshin/apps/strategy.js:114:20)
    at PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai-Bot/lib/plugins/loader.js:247:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by fenggegang** [comment]
#1048 
记得更新版本，新版本这个修复了

**Comment by JalonShaw** [comment]
解决了，谢谢
