### ISSUE TITLE
unknown date format format 和定时任务报错

### ISSUE THREAD

**Issue by 1298509345** [Le-niao/Yunzai-Bot#1117]
fatal: unknown date format format:%m-%d %H:%M

[11:42:39.379][ERRO] Error: Command failed: git log  -1 --oneline --pretty=format:"%cd" --date=format:"%m-%d %H:%M"

fatal: unknown date format format:%m-%d %H:%M

[11:39:07.309][ERRO] Error: Command failed: git log  -1 --oneline --pretty=format:"%cd" --date=format:"%m-%d %H:%M"

}

  erroredSysCall: undefined

  code: 'ECONNRESET',

  errno: 'ECONNRESET',

  type: 'system',

    at async Job.job (file:///home/syg/Yunzai-Bot/lib/plugins/loader.js:586:48) {

    at async mysNewsTask (file:///home/syg/Yunzai-Bot/plugins/genshin/apps/mysNews.js:71:5)

    at async MysNews.mysNewsTask (file:///home/syg/Yunzai-Bot/plugins/genshin/model/mysNews.js:357:16)

    at async MysNews.postData (file:///home/syg/Yunzai-Bot/plugins/genshin/model/mysNews.js:187:17)

    at async Response.json (file:///home/syg/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.2.6/node_modules/node-fetch/src/body.js:148:16)

    at async Response.text (file:///home/syg/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.2.6/node_modules/node-fetch/src/body.js:158:18)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at runMicrotasks (<anonymous>)

    at consumeBody (file:///home/syg/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.2.6/node_modules/node-fetch/src/body.js:234:60)

[09:45:00.948][ERRO] FetchError: Invalid response body while trying to fetch https://bbs-api-static.mihoyo.com/post/wapi/getNewsList?gids=2&page_size=10&type=1: aborted

[09:45:00.947][ERRO] 定时任务报错：米游社公告推送任务

}

    '           <command> [<args>]\n'

    '           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n' +

    '           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]\n' +

    '           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n' +

    'usage: git [--version] [--help] [-c name=value]\n' +

  stderr: 'Unknown option: -C\n' +

  stdout: '',

  pid: 12019,

  ],

      '           <command> [<args>]\n'

      '           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n' +

      '           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]\n' +

      '           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n' +

      'usage: git [--version] [--help] [-c name=value]\n' +

    'Unknown option: -C\n' +

    '',

    null,

  output: [

  signal: null,

  status: 129,

    at autoUpdate.updateAll (file:///home/syg/Yunzai-Bot/plugins/auto-plugin/app/autoUpdate.js:146:18) {

    at autoUpdate.runUpdate (file:///home/syg/Yunzai-Bot/plugins/auto-plugin/app/autoUpdate.js:83:35)

    at autoUpdate.getcommitId (file:///home/syg/Yunzai-Bot/plugins/auto-plugin/app/autoUpdate.js:105:20)

    at execSync (node:child_process:932:15)

    at checkExecSyncError (node:child_process:861:11)

           <command> [<args>]

**Comment by 1298509345** [comment]
还有，我自己ck米游社查询遇到验证码。但是朋友查询是好的
