### ISSUE TITLE
关于#早柚返回MysUser缓存失效这个字段的问题

### ISSUE THREAD

**Issue by wl19961106** [Le-niao/Yunzai-Bot#112]
[2022-05-03T11:57:24.540] [INFO] message - recv from: [Private: 907135212(friend)] #早柚
[2022-05-03T11:57:24.540] [MARK] command - [私聊] #早柚:character
[2022-05-03T11:57:24.542] [ERROR] error - mysInfo.character
[2022-05-03T11:57:24.542] [ERROR] error - TypeError: Invalid argument type
    at encodeCommand (G:\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\RESP2\encoder.js:20:19)
    at RedisCommandsQueue.getCommandToSend (G:\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\commands-queue.js:187:45)
    at Commander._RedisClient_tick (G:\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\index.js:429:76)
    at Commander._RedisClient_sendCommand (G:\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\index.js:413:82)
    at Commander.commandsExecutor (G:\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\index.js:167:154)
    at Commander.BaseClass.<computed> [as zScore] (G:\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\commander.js:8:29)
    at Function.MysUser.isNewTarget (file:///G:/00/Yunzai-Bot/lib/components/models/MysUser.js:449:23)
    at Object.Msg.getMysApi (file:///G:/00/Yunzai-Bot/lib/components/Msg.js:158:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

代码字段如下

**Comment by wl19961106** [comment]
重装了node以及Redis后还是会出现这个问题，以及尝试过安装最新的node+Redis还是出现该问题，当发送指令#早柚以及#其他除了#签到 体力 某某攻略都会出现这个问题
以下是新的问题代码
[2022-05-03T12:51:14.351] [INFO] message - recv from: [Private: 907135212(friend)] #角色
[2022-05-03T12:51:14.351] [MARK] command - [私聊] #角色:roleAll
[2022-05-03T12:51:14.353] [ERROR] error - mysInfo.roleAll
[2022-05-03T12:51:14.353] [ERROR] error - TypeError: Invalid argument type
    at encodeCommand (G:\00\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\RESP2\encoder.js:20:19)
    at RedisCommandsQueue.getCommandToSend (G:\00\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\commands-queue.js:187:45)
    at Commander._RedisClient_tick (G:\00\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\index.js:429:76)
    at Commander._RedisClient_sendCommand (G:\00\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\index.js:413:82)
    at Commander.commandsExecutor (G:\00\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\client\index.js:167:154)
    at BaseClass.<computed> [as zScore] (G:\00\00\Yunzai-Bot\node_modules\_@redis_client@1.1.0@@redis\client\dist\lib\commander.js:8:29)
    at MysUser.isNewTarget (file:///G:/00/00/Yunzai-Bot/lib/components/models/MysUser.js:449:23)
    at Msg.getMysApi (file:///G:/00/00/Yunzai-Bot/lib/components/Msg.js:158:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.getMysApi (file:///G:/00/00/Yunzai-Bot/lib/dealMsg.js:144:12)

**Comment by wl19961106** [comment]
朋友用的版本是2.1.3好像都是正常使用的，我的是最新的2.1.4就会这样，我也不清楚如何回退

**Comment by wl19961106** [comment]
还有请问一下，可不可以在nas中配置机器人，我有个24小时不关的nas希望出一个教程

**Comment by Le-niao** [comment]
删除node_modules，重新 `npm install`

**Comment by wl19961106** [comment]
> 删除node_modules，重新开始`npm install`

已经可以了，感谢大佬，还有就是请问一下nas中可以使用吗，我有内网穿透的nas，这样就不用电脑挂后台
