### ISSUE TITLE
不支持 Nodejs v14.9.0

### ISSUE THREAD

**Issue by Sod-Momas** [Le-niao/Yunzai-Bot#138]
根据测试，nodejs更换为 v15.0.0 后正常，但使用 v14.9.0 会报错，具体信息：
文档里写的是至少需要node 14，那应该是文档错误

```

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ nvm use 14.9.0
Now using node v14.9.0 (64-bit)

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ rm -rf node_modules/

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ node -v
v14.9.0

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ npm -v
6.14.8

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for l
ockfileVersion@2. I'll try to do my best with it!

> puppeteer@13.7.0 install C:\Users\sod\Downloads\git-dir\Yunzai-Bot\node_modules\puppeteer
> node install.js

Downloading Chromium r982053 - 180.5 Mb [====================] 100% 0.0s
Chromium (982053) downloaded to C:\Users\sod\Downloads\git-dir\Yunzai-Bot\node_modules\puppeteer\.local-chromium\win64-98205
3
npm WARN yunzai@2.1.5 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (
current: {"os":"win32","arch":"x64"})

added 448 packages from 793 contributors in 43.132s

34 packages are looking for funding
  run `npm fund` for details


sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ node -v
v14.9.0

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ node app
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol '
node:'
?[90m    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:750:11)?[39m
?[90m    at Loader.resolve (internal/modules/esm/loader.js:85:40)?[39m
?[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)?[39m
?[90m    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)?[39m
?[90m    at link (internal/modules/esm/module_job.js:50:36)?[39m {
  code: ?[32m'ERR_UNSUPPORTED_ESM_URL_SCHEME'?[39m
}

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ nvm use 15.0.0
Now using node v15.0.0 (64-bit)

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ node -v
v15.0.0
n
sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ npm -v
7.0.2

sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$ node app
请按提示输入，生成配置文件config.js，输入错误【Ctrl+c】结束重来
请输入机器人QQ号(请用小号)：
sod@BOOKX MINGW64 ~/Downloads/git-dir/Yunzai-Bot (master)
$

```

![image](https://user-images.githubusercontent.com/17961201/168469327-a45c4932-c1ef-4a7c-8ce1-dbe6cf2af063.png)

**Comment by Sod-Momas** [comment]
另外，环境信息：

```
C:\Users\sod>systeminfo

主机名:           BOOKX
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19043 暂缺 Build 19043
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     sod
注册的组织:       暂缺
产品 ID:          00330-80000-00000-AA602
初始安装日期:     2021/5/4, 17:11:33
系统启动时间:     2022/5/12, 10:42:11
系统制造商:       LENOVO
系统型号:         82MS
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: AMD64 Family 25 Model 80 Stepping 0 AuthenticAMD ~3201 Mhz
BIOS 版本:        LENOVO GZCN20WW, 2021/6/8
Windows 目录:     C:\WINDOWS
系统目录:         C:\WINDOWS\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     14,199 MB
可用的物理内存:   4,016 MB
虚拟内存: 最大值: 17,399 MB
虚拟内存: 可用:   3,958 MB
虚拟内存: 使用中: 13,441 MB
页面文件位置:     C:\pagefile.sys
域:               MOMAS
登录服务器:       \\BOOKX
修补程序:         安装了 13 个修补程序。
                  [01]: KB5013624
                  [02]: KB4562830
                  [03]: KB4570334
                  [04]: KB4577586
                  [05]: KB4580325
                  [06]: KB5000736
                  [07]: KB5013942
                  [08]: KB5006753
                  [09]: KB5007273
                  [10]: KB5011352
                  [11]: KB5011651
                  [12]: KB5014032
                  [13]: KB5005699
网卡:             安装了 5 个 NIC。
                  [01]: Intel(R) Wi-Fi 6 AX200 160MHz
                      连接名:      WLAN
                      状态:        媒体连接已中断
                  [02]: Bluetooth Device (Personal Area Network)
                      连接名:      蓝牙网络连接
                      状态:        媒体连接已中断
                  [03]: Hyper-V Virtual Ethernet Adapter
                      连接名:      vEthernet (Default Switch)
                      启用 DHCP:   否
                      IP 地址
                        [01]: 172.22.96.1
                        [02]: fe80::2852:754f:1d5d:db3b
                  [04]: VirtualBox Host-Only Ethernet Adapter
                      连接名:      VirtualBox Host-Only Network
                      启用 DHCP:   否
                      IP 地址
                        [01]: 192.168.56.1
                        [02]: fe80::3530:7b75:eb4:3e55
                  [05]: Realtek USB FE Family Controller
                      连接名:      以太网
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.0.1
                      IP 地址
                        [01]: 192.168.0.110
                        [02]: fe80::c8ff:7d7e:3631:e0ff
Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。

```

**Comment by Sod-Momas** [comment]
参考文档 ： 原神机器人Yunzai-Bot window搭建教程 https://www.bilibili.com/read/cv15119056

**Comment by Le-niao** [comment]
升级node16，低版本node不支持ESM
