### ISSUE TITLE
未绑定cookie的账号发送 #刻晴（类似这种信息）会出现cookieUser.getCookie is not a function     at Object.Msg.getMysApi

### ISSUE THREAD

**Issue by snowluvletter** [Le-niao/Yunzai-Bot#148]
TypeError: cookieUser.getCookie is not a function
    at Object.Msg.getMysApi (file:///E:/gitHouse/Yunzai-Bot/lib/components/Msg.js:170:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GroupMessage.e.getMysApi (file:///E:/gitHouse/Yunzai-Bot/lib/dealMsg.js:144:12)
    at async getMysApi (file:///E:/gitHouse/Yunzai-Bot/lib/app/mysInfo.js:122:10)
    at async Module.character (file:///E:/gitHouse/Yunzai-Bot/lib/app/mysInfo.js:1349:16)
    at async Object.dealMsg (file:///E:/gitHouse/Yunzai-Bot/lib/dealMsg.js:191:19)

**Comment by Le-niao** [comment]
去config.js配置下公共cookie

**Comment by zizxzy** [comment]
你好，请问最后是怎么解决的，我也出现同样的错误
