### ISSUE TITLE
linux环境，查询的时候cookie错误

### ISSUE THREAD

**Issue by zizxzy** [Le-niao/Yunzai-Bot#161]
在使用云服务器搭建机器人之后，进行查询，输入#角色名，会出现下列错误
mysInfo.character
TypeError: cookieUser.getCookie is not a function
    at Object.Msg.getMysApi (file:///root/Yunzai-Bot/lib/components/Msg.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GroupMessage.e.getMysApi (file:///root/Yunzai-Bot/lib/dealMsg.js:144:12)
    at async getMysApi (file:///root/Yunzai-Bot/lib/app/mysInfo.js:122:10)
    at async Module.character (file:///root/Yunzai-Bot/lib/app/mysInfo.js:1349:16)
    at async Object.dealMsg (file:///root/Yunzai-Bot/lib/dealMsg.js:191:19)
请问大佬这个要怎么处理呀？

**Comment by zizxzy** [comment]
已解决

**Comment by davidelectricfree** [comment]
你怎么处理的？我遇到的情况是CK没问题，有的人能查询，有的人无法查询

**Comment by NomadThanatos** [comment]
Duplicate as #148
