### ISSUE TITLE
在设置好公共CK的情况下，极个别成员查看角色信息会报错

### ISSUE THREAD

**Issue by davidelectricfree** [Le-niao/Yunzai-Bot#164]
重做了服务器系统以后，设置公共CK，在所有人都没有绑定私人CK的情况下，绝大部分人能正常使用角色卡牌功能，极少数群员无法使用查询信息功能：如老婆，角色卡牌等，报错信息如下所示。

[2022-05-22T22:50:35.831] [MARK] command - [xxx] #角色卡片:character
[2022-05-22T22:50:35.834] [MARK] command - [xxx] #角色卡片:roleCard
[2022-05-22T22:50:35.836] [ERROR] error - mysInfo.roleCard
[2022-05-22T22:50:35.837] [ERROR] error - TypeError: cookieUser.getCookie is not a function
at Object.Msg.getMysApi (file:///C:/GenshinBot/Yunzai-Bot/lib/components/Msg.js:170:25)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async GroupMessage.e.getMysApi (file:///C:/GenshinBot/Yunzai-Bot/lib/dealMsg.js:144:12)
at async getMysApi (file:///C:/GenshinBot/Yunzai-Bot/lib/app/mysInfo.js:122:10)
at async Module.roleCard (file:///C:/GenshinBot/Yunzai-Bot/lib/app/mysInfo.js:515:16)
at async Object.dealMsg (file:///C:/GenshinBot/Yunzai-Bot/lib/dealMsg.js:191:19)

**Comment by NomadThanatos** [comment]
Duplicate as #148.
