### ISSUE TITLE
体力提交cookie报错了

### ISSUE THREAD

**Issue by smlily** [Le-niao/Yunzai-Bot#19]
`[root@smlily Yunzai-Bot]# node app 
/www/wwwroot/bot/Yunzai-Bot/app.js:1
(function (exports, require, module, __filename, __dirname) { import { createClient } from "oicq";
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)`
请问我应该怎么办？

**Comment by Le-niao** [comment]
升级Nodejs

**Comment by smlily** [comment]
> 升级Nodejs

需要升级到多少

**Comment by Le-niao** [comment]
> > 升级Nodejs
> 
> 需要升级到多少

至少v14
