### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'uid')

### ISSUE THREAD

**Issue by wayne0926** [Le-niao/Yunzai-Bot#222]
```
                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.Configuration.getAllSync (/www/wwwroot/yuans/Yunzai-Bot/node_modules/pm2/lib/Configuration.js:299:26)
    at Object.Configuration.getSync (/www/wwwroot/yuans/Yunzai-Bot/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/www/wwwroot/yuans/Yunzai-Bot/node_modules/pm2/lib/API.js:116:44)
    at Object.<anonymous> (/www/wwwroot/yuans/Yunzai-Bot/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
/www/wwwroot/yuans/Yunzai-Bot/node_modules/@pm2/agent/src/InteractorClient.js:58
          if (stats.uid === 0) {
                    ^

TypeError: Cannot read properties of undefined (reading 'uid')
    at /www/wwwroot/yuans/Yunzai-Bot/node_modules/@pm2/agent/src/InteractorClient.js:58:21
    at FSReqCallback.oncomplete (node:fs:198:21)
```

`node app`启动比较正常，但是`npm start`就这样报错，该怎么解决

**Comment by iCdo-X** [comment]
我也遇到这个问题了 求解决

**Comment by SirlyDreamer** [comment]
看起来似乎是权限问题，sudo试试

**Comment by iCdo-X** [comment]
> 看起来似乎是权限问题，sudo试试

是用的root用户

**Comment by iCdo-X** [comment]
> 加上sudo就显示未找到命令了

**Comment by SirlyDreamer** [comment]
先su root，不好意思忽略了环境变量

**Comment by SirlyDreamer** [comment]
搜索了一下，发现是pm2的问题：https://github.com/Unitech/pm2/issues/487

这个问题应该在2014年就已经被修复了才对（死去的issue又开始攻击我QwQ

如果不介意的话，尝试docker部署？只需要用脚本安装然后移动覆盖相应文件夹即可

安装方法：[https://github.com/Le-niao/Yunzai-Bot/issues/80](https://github.com/Le-niao/Yunzai-Bot/issues/80)

**Comment by iCdo-X** [comment]
> 搜索了一下，发现是pm2的问题：[Unitech/pm2#487](https://github.com/Unitech/pm2/issues/487)
> 
> 这个问题应该在2014年就已经被修复了才对（死去的issue又开始攻击我QwQ
> 
> 如果不介意的话，尝试docker部署？只需要用脚本安装然后移动覆盖相应文件夹即可
> 
> 安装方法：#80

那个问题有办法解决吗

**Comment by iCdo-X** [comment]
解决了，用chown -R root:root Yunzai-Bot/，似乎就是权限的问题
