### ISSUE TITLE
首次配置时出现typeerror错误

### ISSUE THREAD

**Issue by Nuist666** [Le-niao/Yunzai-Bot#231]
C:\Users\DELL\Yunzai-Bot\node_modules\.pnpm\oicq@2.3.1\node_modules\oicq\lib\core\device.js:47
        wifi_ssid: `TP-LINK-${uin.toString(16)}`,
                                  ^

TypeError: Cannot read properties of null (reading 'toString')
    at generateShortDevice (C:\Users\DELL\Yunzai-Bot\node_modules\.pnpm\oicq@2.3.1\node_modules\oicq\lib\core\device.js:47:35)
    at new Client (C:\Users\DELL\Yunzai-Bot\node_modules\.pnpm\oicq@2.3.1\node_modules\oicq\lib\client.js:56:57)
    at new Yunzai (file:///C:/Users/DELL/Yunzai-Bot/lib/bot.js:8:5)
    at Function.run (file:///C:/Users/DELL/Yunzai-Bot/lib/bot.js:15:17)
    at file:///C:/Users/DELL/Yunzai-Bot/app.js:4:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Le-niao** [comment]
按提示输入qq号和密码，不填跳过的话，就会直接报错

**Comment by Nuist666** [comment]
我填了，扫码登录之后跳出来的

**Comment by Nuist666** [comment]
但是再次输入node app再扫码就没有报错可以正常运行

**Comment by Nuist666** [comment]
只是第一次配置会遇到这个情况，不知道为什么

**Comment by Nuist666** [comment]
之前用的2.1.8版本没有出现这个问题

**Comment by Le-niao** [comment]
只有不输qq号才有这个报错，现在增加了验证，qq号变为必填
