### ISSUE TITLE
QQ登录成功后初始化时错误

### ISSUE THREAD

**Issue by regjuan** [Le-niao/Yunzai-Bot#28]
[2022-03-11T10:50:09.254] [MARK] [Android:1933902207] - 初始化Yunzai-Bot
[2022-03-11T10:50:09.461] [ERROR] [Android:1933902207] - 报错：global.js
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at new NodeError (node:internal/errors:371:5)
    at Object.watch (node:fs:2247:11)
    at watchFile (file:///root/Yunzai-Bot/lib/app/global.js:105:6)
    at init (file:///root/Yunzai-Bot/lib/app/global.js:63:3)
    at file:///root/Yunzai-Bot/lib/app/global.js:28:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadApp (file:///root/Yunzai-Bot/lib/init.js:153:19)
    at async init (file:///root/Yunzai-Bot/lib/init.js:82:33) {
  code: 'ERR_FEATURE_UNAVAILABLE_ON_PLATFORM'
}

**Comment by Le-niao** [comment]
迟点看看有点忙

**Comment by regjuan** [comment]
好的 感谢
系统是Ubuntu20

**Comment by Le-niao** [comment]
> 好的 感谢 系统是Ubuntu20

重新拉下可以了
