### ISSUE TITLE
Linux环境搭建

### ISSUE THREAD

**Issue by Le-niao** [Le-niao/Yunzai-Bot#3]
### linux服务器环境搭建
这里以腾讯轻量应用服务器CentOS 8.2为例。
选择**Node.js**镜像

![Node.js镜像](https://user-images.githubusercontent.com/12881780/142713197-f71909a8-7e95-4fb7-8059-a608a410b8e2.png)

创建好后登录服务器
切换root权限
`sudo -i `

#### 安装git   (输入y确定，后续一样)
`yum install git `

#### 安装并运行redis
`yum install redis`
`systemctl start redis.service`

#### 克隆Yunzai-Bot 
`git clone https://github.com/Le-niao/Yunzai-Bot.git`
`cd Yunzai-Bot`

#### 切换npm镜像
`npm install cnpm -g --registry=https://registry.npm.taobao.org`

#### 用cnpm安装，主要安装Puppeteer，下载chrome浏览器
`cnpm install`

![Puppeteer安装](https://user-images.githubusercontent.com/12881780/142713344-2edce80a-00b0-46c3-8fa9-df969f7941e9.png)

#### 安装chrome依赖库
`yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y`
`yum install nss -y`
`yum install libdrm libgbm libxshmfence -y`
`yum update nss -y`

#### 安装中文字体
`yum install fontconfig`
`yum install mkfontscale`

**上传**中文字体文件到 /usr/share/fonts/
推荐用微软雅黑.tff

建立字体索引信息，更新字体缓存
`cd /usr/share/fonts/`
`mkfontscale`
`mkfontdir`

#### 运行
`node app`

要后台运行的自己安装forever或者pm2
`npm install forever -g`
`forever start app.js`

#### 运行成功
![运行成功](https://user-images.githubusercontent.com/12881780/142713517-530e74b2-e496-4cbd-b5c8-e5a27b505f49.png)

**Comment by shiroringo** [comment]
求更新一下gitee源

**Comment by xueshuaib** [comment]
这个搭建怎么找到文件修改配置

**Comment by Aphlos1530** [comment]
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct` Chromium revision (982053).

**Comment by xwt000203** [comment]
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 206_122_285_581

**Comment by Code-thieves** [comment]
[2022-05-07T23:32:28.894] [MARK] command - [私聊] 帮助:help
[2022-05-07T23:32:28.930] [MARK] command - puppeteer 启动中。。
[2022-05-07T23:32:29.188] [MARK] command - puppeteer 启动成功
要生成的图片一律不回

**Comment by Abortbeen** [comment]
linux 输出的角色卡片是乱码 的怎么解决呀

**Comment by Abortbeen** [comment]
无法显示中文

**Comment by Le-niao** [comment]
> 无法显示中文

安装中文字体
`yum groupinstall fonts -y`

**Comment by L-yt** [comment]
linux搭建的话是不是项目更新了就只能拉下来覆盖

**Comment by RealHeart** [comment]
建议更新脚本，将安装chrome放到 安装npm依赖前面 现在的版本npm会自动访问谷歌安装chrome 导致国内服务器卡住

**Comment by DrAugus** [comment]
`npm install cnpm -g --registry=https://registry.npm.taobao.org` 这个安装炒鸡慢鸭

**Comment by llightos** [comment]
有无更新命令？

**Comment by RealHeart** [comment]
> 有无更新命令？

使用机器人命令:
#更新
#重启

或命令行:
git pull && npm i && npm restart

**Comment by Bai3396** [comment]
[2022-06-07T21:49:47.557] [ERROR] [iMac:484436257] - 报错：global.js
Error: ENOENT: no such file or directory, scandir './resources/global_img'
    at Object.readdirSync (node:fs:1405:3)
    at readdirectory (file:///opt/Yunzai-Bot/lib/app/global.js:71:18)
    at init (file:///opt/Yunzai-Bot/lib/app/global.js:64:3)
    at file:///opt/Yunzai-Bot/lib/app/global.js:25:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadApp (file:///opt/Yunzai-Bot/lib/init.js:171:19)
    at async init (file:///opt/Yunzai-Bot/lib/init.js:47:3)
    at async Client.<anonymous> (file:///opt/Yunzai-Bot/app.js:51:3) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './resources/global_img'
}

**Comment by username-long111** [comment]
关闭登录保护还要验证码，需要怎么发送

**Comment by QYYJN** [comment]
![IMG_20220609_081103.jpg](https://user-images.githubusercontent.com/99798803/172737843-26f757f8-17d4-479d-b9d5-8925e3653904.jpg)这怎么回事

**Comment by Yamakoer** [comment]
cnpm install时报错
![微信图片_20220612013211](https://user-images.githubusercontent.com/53447185/173217182-57006608-7537-4b8e-afcc-322344109621.png)

**Comment by Kevinli1987** [comment]
能不能做一个微信版本的机器人，改一下接口代码

**Comment by RUSSELL987** [comment]
sill idealTree buildDeps
cnpm安装失败
换过淘宝和npmmirror镜像还是不行
腾讯云上挂不了梯子...
佬佬，救救

**Comment by Kevinli1987** [comment]
您好，我已经收到您的邮件！

**Comment by xiaoli8808** [comment]
我的中文字库怎么装不上啊

**Comment by Kevinli1987** [comment]
您好，我已经收到您的邮件！

**Comment by xiaoli8808** [comment]
我中文字库装上怎么显示的还是点点就跟没装上似的

**Comment by Happygoing-ding** [comment]
能否提供一个低版本2.1.8的克隆链接，现在已经找不到之前的版本了

**Comment by 507840158** [comment]
![image](https://user-images.githubusercontent.com/89287398/183027450-48955d6d-0de8-4d66-8e12-b0621d1a3269.png)
一键安装这样了，怎么回事

**Comment by JiJiang233** [comment]
自动搭建脚本的链接失效了wwwwwwwwwwwwwwwwwww

**Comment by zangxycoding** [comment]
自动脚本能修复一下吗?

**Comment by 526882956** [comment]
![image](https://user-images.githubusercontent.com/45258309/188080885-33789f40-8109-4f6b-98d9-fb394973f967.png)
这些个报错是啥意思啊，还有输入指令为什么都是角色查询呢

**Comment by Kevinli1987** [comment]
您好，我已经收到您的邮件！

**Comment by jiexi22** [comment]
[root@VM-20-14-centos Yunzai-Bot]# npm start

> yunzai@3.0.0 start
> pm2 start ./config/pm2/pm2.json

[PM2] Applying action restartProcessId on app [Yunzai-Bot](ids: [ 1 ])
[PM2][ERROR] Process 1 not found
Process 1 not found
/root/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:1717
        acted.push(proc.pm2_env ? proc.pm2_env.pm_id : proc.pm_id)
                        ^

TypeError: Cannot read properties of undefined (reading 'pm2_env')
    at /root/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:1717:25
    at Array.forEach (<anonymous>)
    at API.speedList (/root/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:1716:18)
    at /root/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/binaries/CLI.js:301:15
    at wrapper (/root/Yunzai-Bot/node_modules/.pnpm/async@3.2.4/node_modules/async/internal/once.js:12:16)
    at replenish (/root/Yunzai-Bot/node_modules/.pnpm/async@3.2.4/node_modules/async/internal/eachOfLimit.js:76:25)
    at iterateeCallback (/root/Yunzai-Bot/node_modules/.pnpm/async@3.2.4/node_modules/async/internal/eachOfLimit.js:65:17)
    at /root/Yunzai-Bot/node_modules/.pnpm/async@3.2.4/node_modules/async/internal/onlyOnce.js:12:16
    at /root/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/binaries/CLI.js:292:11
    at /root/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:330:21

**Comment by YemingQing** [comment]
可以弄成微信群聊的接口吗

**Comment by SunnerSun** [comment]
```
node:internal/modules/cjs/loader:956
  const err = new Error(message);
              ^

Error: Cannot find module '@redis/client/dist/lib/commands/generic-transformers'
Require stack:
- /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js
- /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/index.js
- /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/index.js
- /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js:9:30)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js',
    '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/index.js',
    '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/index.js',
    '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/index.js'
  ]
}
```

最后启动机器人（node app）的时候报了这个错误，大家有遇到么？

**Comment by Kevinli1987** [comment]
您好，我已经收到您的邮件！

**Comment by jyh111** [comment]
> ```
> node:internal/modules/cjs/loader:956
>   const err = new Error(message);
>               ^
> 
> Error: Cannot find module '@redis/client/dist/lib/commands/generic-transformers'
> Require stack:
> - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js
> - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/index.js
> - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/index.js
> - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/index.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
>     at Module.require (node:internal/modules/cjs/loader:1028:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js:9:30)
>     at Module._compile (node:internal/modules/cjs/loader:1126:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
>     at Module.load (node:internal/modules/cjs/loader:1004:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
>     at Module.require (node:internal/modules/cjs/loader:1028:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js',
>     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/index.js',
>     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/index.js',
>     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/index.js'
>   ]
> }
> ```
> 
> 最后启动机器人（node app）的时候报了这个错误，大家有遇到么？

我也遇到了这个问题 第一次启动

**Comment by jyh111** [comment]
> > ```
> > node:internal/modules/cjs/loader:956
> >   const err = new Error(message);
> >               ^
> > 
> > Error: Cannot find module '@redis/client/dist/lib/commands/generic-transformers'
> > Require stack:
> > - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js
> > - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/index.js
> > - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/index.js
> > - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/index.js
> >     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
> >     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
> >     at Module.require (node:internal/modules/cjs/loader:1028:19)
> >     at require (node:internal/modules/cjs/helpers:102:18)
> >     at Object.<anonymous> (/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js:9:30)
> >     at Module._compile (node:internal/modules/cjs/loader:1126:14)
> >     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
> >     at Module.load (node:internal/modules/cjs/loader:1004:32)
> >     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
> >     at Module.require (node:internal/modules/cjs/loader:1028:19) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [
> >     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js',
> >     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/index.js',
> >     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/index.js',
> >     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/index.js'
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最后启动机器人（node app）的时候报了这个错误，大家有遇到么？
> 
> 我也遇到了这个问题 第一次启动

我弄好了，应该是去npm安装指定版本的redis ·cnpm install redis==4.0.1`

**Comment by jyh111** [comment]
> > ```
> > node:internal/modules/cjs/loader:956
> >   const err = new Error(message);
> >               ^
> > 
> > Error: Cannot find module '@redis/client/dist/lib/commands/generic-transformers'
> > Require stack:
> > - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js
> > - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/index.js
> > - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/index.js
> > - /root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/index.js
> >     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
> >     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
> >     at Module.require (node:internal/modules/cjs/loader:1028:19)
> >     at require (node:internal/modules/cjs/helpers:102:18)
> >     at Object.<anonymous> (/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js:9:30)
> >     at Module._compile (node:internal/modules/cjs/loader:1126:14)
> >     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
> >     at Module.load (node:internal/modules/cjs/loader:1004:32)
> >     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
> >     at Module.require (node:internal/modules/cjs/loader:1028:19) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [
> >     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/ADD.js',
> >     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/bloom/index.js',
> >     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/commands/index.js',
> >     '/root/Yunzai-Bot/node_modules/_@redis_bloom@1.0.2@@redis/bloom/dist/index.js'
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最后启动机器人（node app）的时候报了这个错误，大家有遇到么？
> 
> 我也遇到了这个问题 第一次启动

我弄好了，应该是安装指定package.json版本的redis
`cnpm install redis@4.0.1`
或者可以考虑关掉再重启redis服务

**Comment by SunnerSun** [comment]
十分感谢，我去试一试

**Comment by yushengjiaohuang** [comment]
自动脚本失效了

**Comment by sacckura** [comment]
如何后台保持运行？？

**Comment by Kevinli1987** [comment]
您好，我已经收到您的邮件！
