### ISSUE TITLE
程序无法后台运行

### ISSUE THREAD

**Issue by minerva0394** [Le-niao/Yunzai-Bot#359]
使用node app命令时能正常运行
但是使用npm start的时候报错，麻烦看看是什么问题
![image](https://user-images.githubusercontent.com/58332372/183080132-0a438066-d16f-4af5-a740-7dca5a9a7231.png)

**Comment by minerva0394** [comment]
Error: Command failed: npm run start
[PM2][ERROR] Process 0 not found
Process 0 not found
/root/Yunzai-Bot/node_modules/_pm2@5.2.0@pm2/lib/API.js:1717
        acted.push(proc.pm2_env ? proc.pm2_env.pm_id : proc.pm_id)
                        ^

TypeError: Cannot read properties of undefined (reading 'pm2_env')
    at /root/Yunzai-Bot/node_modules/_pm2@5.2.0@pm2/lib/API.js:1717:25
    at Array.forEach (<anonymous>)
    at API.speedList (/root/Yunzai-Bot/node_modules/_pm2@5.2.0@pm2/lib/API.js:1716:18)
    at /root/Yunzai-Bot/node_modules/_pm2@5.2.0@pm2/lib/binaries/CLI.js:301:15
    at wrapper (/root/Yunzai-Bot/node_modules/_async@3.2.4@async/internal/once.js:12:16)
    at replenish (/root/Yunzai-Bot/node_modules/_async@3.2.4@async/internal/eachOfLimit.js:76:25)
    at iterateeCallback (/root/Yunzai-Bot/node_modules/_async@3.2.4@async/internal/eachOfLimit.js:65:17)
    at /root/Yunzai-Bot/node_modules/_async@3.2.4@async/internal/onlyOnce.js:12:16
    at /root/Yunzai-Bot/node_modules/_pm2@5.2.0@pm2/lib/binaries/CLI.js:292:11
    at /root/Yunzai-Bot/node_modules/_pm2@5.2.0@pm2/lib/API.js:330:21

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by ctrlcvs** [comment]
pm2不行  下次建议百度后再来问，这种情况引入包文件就好了pnpm add pm2或者用cnpm i pm2 以及 npm i pm2 大概率是pnpm权限导致包文件下载不是最新的建议换cnpm更新下看看

**Comment by minerva0394** [comment]
> pm2不行 下次建议百度后再来问，这种情况引入包文件就好了pnpm add pm2或者用cnpm i pm2 以及 npm i pm2 大概率是pnpm权限导致包文件下载不是最新的建议换cnpm更新下看看

感谢，确实是pm2不行，先尝试了一波pm2 update就可以了，再次感谢
