### ISSUE TITLE
puppeteer启动失败

### ISSUE THREAD

**Issue by tsurumi-yizhou** [Le-niao/Yunzai-Bot#389]
环境：raspberry pi 4B，raspbian 11，node 16.16.0
```
[YzBot][18:51:51.227][MARK] puppeteer Chromium 启动中。。
[YzBot][18:51:51.286][ERRO] Error: Failed to launch the browser process!
/home/pi/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: 16: Syntax error: ")" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/pi/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/home/pi/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:539:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[YzBot][18:51:51.290][ERRO] puppeteer Chromium 启动失败
```

**Comment by tsurumi-yizhou** [comment]
架构是arm v71

**Comment by tsurumi-yizhou** [comment]
已解决，可将lib/puppeteer/puppeteer.js中的executePath设置为/usr/bin/chromium。
