### ISSUE TITLE
plugins/genshin/config目录相关问题

### ISSUE THREAD

**Issue by wzwzx** [Le-niao/Yunzai-Bot#530]
[YzBot][17:02:38.441][ERRO] Error: ENOENT: no such file or directory, copyfile '
./plugins/genshin/defSet/gacha/set.yaml' -> './plugins/genshin/config/gacha.set.
yaml'
    at Object.copyFileSync (node:fs:2817:3)
    at gacha.init (file:///root/Yunzai-Bot/plugins/genshin/apps/gacha.js:128:8)
    at PluginsLoader.runInit (file:///root/Yunzai-Bot/lib/plugins/loader.js:95:2
7)
    at file:///root/Yunzai-Bot/lib/plugins/loader.js:61:16
    at /root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lo
dash.js:4967:15
    at baseForOwn (/root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modul
es/lodash/lodash.js:3032:24)
    at /root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lo
dash.js:4936:18
    at Function.forEach (/root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node
_modules/lodash/lodash.js:9410:14)
    at PluginsLoader.load (file:///root/Yunzai-Bot/lib/plugins/loader.js:52:16)
    at async onlineEvent.execute (file:///root/Yunzai-Bot/lib/events/online.js:2
3:5) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './plugins/genshin/defSet/gacha/set.yaml',
  dest: './plugins/genshin/config/gacha.set.yaml'
}
[YzBot][17:02:38.442][ERRO] Error: ENOENT: no such file or directory, copyfile '
./plugins/genshin/defSet/mys/pubCk.yaml' -> './plugins/genshin/config/mys.pubCk.
yaml'
    at Object.copyFileSync (node:fs:2817:3)
    at role.init (file:///root/Yunzai-Bot/plugins/genshin/apps/role.js:68:10)
    at PluginsLoader.runInit (file:///root/Yunzai-Bot/lib/plugins/loader.js:95:2
7)
    at file:///root/Yunzai-Bot/lib/plugins/loader.js:61:16
    at /root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lo
dash.js:4967:15
    at baseForOwn (/root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modul
es/lodash/lodash.js:3032:24)
    at /root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lo
dash.js:4936:18
    at Function.forEach (/root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node
_modules/lodash/lodash.js:9410:14)
    at PluginsLoader.load (file:///root/Yunzai-Bot/lib/plugins/loader.js:52:16)
    at async onlineEvent.execute (file:///root/Yunzai-Bot/lib/events/online.js:2
3:5) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './plugins/genshin/defSet/mys/pubCk.yaml',
  dest: './plugins/genshin/config/mys.pubCk.yaml'

**Comment by rgdsmint** [comment]
so how to solve,please?

**Comment by wzwzx** [comment]
> 

cd Yunzai-Bot
mkdir plugins/genshin/config

**Comment by wzwzx** [comment]
> so how to solve,please?

Create your own config folder in the plugins/genshin directory
