### ISSUE TITLE
腾讯智能对话平台TBP报错

### ISSUE THREAD

**Issue by Xm798** [Le-niao/Yunzai-Bot#55]
日志
```
[2022-04-06T10:40:34.860] [ERROR] error - ai.tencentAI
[2022-04-06T10:40:34.860] [ERROR] error - TencentCloudSDKHttpException [Error]: GetRobotBasicInfo failed, [err:rpc error: code = Unknown desc = robot not complied or robot not exist or robot offline]
    at Client.parseResponse (/app/Yunzai-Bot/node_modules/_tencentcloud-sdk-nodejs@4.0.319@tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:134:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.request (/app/Yunzai-Bot/node_modules/_tencentcloud-sdk-nodejs@4.0.319@tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:65:28)
    at async Module.tencentAI (file:///app/Yunzai-Bot/lib/app/ai.js:136:13)
    at async Object.dealMsg (file:///app/Yunzai-Bot/lib/dealMsg.js:179:19) {
  requestId: '912fa251-b067-483b-b9b1-e4058cd069ae',
  code: 'InternalError.ErrorRpc'
```

配置部分
```
tencentAI: {
      secretId: "Axxxxxxxxxxxxxxx1",//云产品-管理与审计-访问秘钥获取
      secretKey: "Bxxxxxxxxxxxxxxxw",//云产品-管理与审计-访问秘钥获取
      BotId: "3xxxxxxxxxxxxxxx9",//腾讯智能对话平台-Bot信息-BotId
      BotEnv: "dev",//不用管就填dev
      BotName: "云崽",//机器人名称
    },
```

子用户权限策略已关联 `QcloudTBPFullAccess`，已开启API密钥
![image](https://user-images.githubusercontent.com/48074861/161885212-32630b7c-01ff-4cde-929c-a75351bd97b1.png)
![image](https://user-images.githubusercontent.com/48074861/161884864-05659af2-68dc-43b9-96c0-8a42651c6d93.png)

**Comment by Le-niao** [comment]
创建下机器人再开启闲聊试试
![QQ截图20220406104930](https://user-images.githubusercontent.com/12881780/161886431-9fa6a77f-b0c1-433e-9483-067e62c008e7.png)

**Comment by Xm798** [comment]
机器人创建过了，闲聊一直开着的
![image](https://user-images.githubusercontent.com/48074861/161887071-eb3335bb-3338-4cf6-aec1-cdb0dd98fbc5.png)

**Comment by Le-niao** [comment]
可以用这个[API Explorer](https://console.cloud.tencent.com/api/explorer?Product=tbp&Version=2019-06-27&Action=TextProcess&SignVersion=)调试下，看下能不能调用

**Comment by Xm798** [comment]
> 可以用这个[API Explorer](https://console.cloud.tencent.com/api/explorer?Product=tbp&Version=2019-06-27&Action=TextProcess&SignVersion=)调试下，看下能不能调用

可以的耶
![image](https://user-images.githubusercontent.com/48074861/161916424-49575506-7e54-44df-ae9a-fb5d5de3b731.png)

**Comment by Xm798** [comment]
botid没错，换用主账号API密钥是正常了，切换到子账号API密钥就报错，貌似QcloudTBPFullAccess这个策略权限不对或者权限不够，是不是还用到了其他什么权限？
![image](https://user-images.githubusercontent.com/48074861/161919889-5f76261c-631b-480c-9038-ab360d10a63d.png)
