### ISSUE TITLE
定时任务报错：查询人物动作是否完成

### ISSUE THREAD

**Issue by DDGG123** [Le-niao/Yunzai-Bot#601]
[YzBot][01:04:00.045][ERRO] 定时任务报错：查询人物动作是否完成
[YzBot][01:04:00.046][ERRO] TypeError: Cannot read properties of undefined (reading 'length')
    at SecretPlaceTask.Secretplacetask (file:///F:/yunzai/Yunzai-Bot/plugins/xiuxian-emulator-plugin/apps/SecretPlaceTask.js:136:82)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.job (file:///F:/yunzai/Yunzai-Bot/lib/plugins/loader.js:581:48)

**Comment by DDGG123** [comment]
我在上个issue提到的ENOENT无法解决，迫不得已使用了npm进行安装，不知道是否会对此错误产生影响，无法使用pnpm可能和我把云崽搭在了u盘上有关，我后来在桌面搭了一个就看起来没问题，只是电脑空间不足了。用npm安装依赖的云崽目前运行状态良好，功能暂时也没有问题，只有这个报错时不时弹一下

**Comment by ctrlcvs** [comment]
> [YzBot][01:04:00.045][ERRO] 定时任务报错：查询人物动作是否完成 [YzBot][01:04:00.046][ERRO] TypeError: Cannot read properties of undefined (reading 'length') at SecretPlaceTask.Secretplacetask (file:///F:/yunzai/Yunzai-Bot/plugins/xiuxian-emulator-plugin/apps/SecretPlaceTask.js:136:82) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Job.job (file:///F:/yunzai/Yunzai-Bot/lib/plugins/loader.js:581:48)

这个是修仙插件的功能报错，建议去修仙的gitee提issue
