### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by chenshoyuan** [Le-niao/Yunzai-Bot#61]
[2022-04-08T12:34:30.820] [MARK] command - [原神频道] #角色114004808:roleAll
[2022-04-08T12:34:32.099] [MARK] command - puppeteer 启动中。。
[2022-04-08T12:34:32.102] [ERROR] error - Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (970485).
    at ChromeLauncher.launch (C:\Users\Administrator\Desktop\Yunzai-Bot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:101:23)
    at async browserInit (file:///C:/Users/Administrator/Desktop/Yunzai-Bot-master/lib/render.js:178:13)
    at async doRender (file:///C:/Users/Administrator/Desktop/Yunzai-Bot-master/lib/render.js:109:9)
    at async render (file:///C:/Users/Administrator/Desktop/Yunzai-Bot-master/lib/render.js:50:10)
    at async Module.roleAll (file:///C:/Users/Administrator/Desktop/Yunzai-Bot-master/lib/app/mysInfo.js:268:16)
    at async Object.dealMsg (file:///C:/Users/Administrator/Desktop/Yunzai-Bot-master/lib/dealMsg.js:179:19)
[2022-04-08T12:34:32.104] [ERROR] error - puppeteer 启动失败

**Comment by Le-niao** [comment]
安装chrome浏览器  `node ./node_modules/puppeteer/install.js`

**Comment by Le-niao** [comment]
> 安装chrome浏览器 `node ./node_modules/puppeteer/install.js`

不行的用`cnpm install puppeteer`安装
