### ISSUE TITLE
最近一周一直无法#更新面板

### ISSUE THREAD

**Issue by YvetteVv** [Le-niao/Yunzai-Bot#614]
显示“请求失败，服务器负载较高”

log报错是这样
```
YzBot][22:52:00.010][ERRO] 定时任务报错：查询人物动作是否完成
0|Yunzai-B | [YzBot][22:52:00.011][ERRO] TypeError: Cannot read properties of undefined (reading 'biguan')
0|Yunzai-B |     at PlayerControlTask.Playercontroltask (file:///home/lighthouse/bot/Yunzai-Bot/plugins/xiuxian-emulator-plugin/apps/PlayerControlTask.js:82:57)
0|Yunzai-B |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Yunzai-B |     at async Job.job (file:///home/lighthouse/bot/Yunzai-Bot/lib/plugins/loader.js:581:48)
0|Yunzai-B | [YzBot][22:53:18.455][ERRO] redis错误:Error: Socket closed unexpectedly
```

**Comment by mkroen** [comment]
喵喵插件换个节点可以解决

**Comment by lingyu0628** [comment]
> 喵喵插件换个节点可以解决

请问怎么更换节点呢，是与要更改那个文件呢?感谢·

**Comment by lingyu0628** [comment]
> 喵喵插件换个节点可以解决

请问怎么更换节点呢，是要更改那个文件呢?感谢·

**Comment by mkroen** [comment]
> > 喵喵插件换个节点可以解决
> 
> 请问怎么更换节点呢，是要更改那个文件呢?感谢·

[https://github.com/yoimiya-kokomi/miao-plugin/issues/63](url)
