### ISSUE TITLE
云崽启动报没有权限打开日志

### ISSUE THREAD

**Issue by 1851951314** [Le-niao/Yunzai-Bot#649]
今天服务器关机重启了，然后报错如下：
lighthouse@VM-16-7-centos Yunzai-Bot]$ node app
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, open 'logs/command.2022-09-28.log'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2153:35)
    at Object.appendFileSync (node:fs:2215:6)
    at DateRollingFileStream._renewWriteStream (/usr/src/Yunzai-Bot/node_modules/.pnpm/streamroller@3.1.1/node_modules/streamroller/lib/RollingFileWriteStream.js:312:8)
    at new RollingFileWriteStream (/usr/src/Yunzai-Bot/node_modules/.pnpm/streamroller@3.1.1/node_modules/streamroller/lib/RollingFileWriteStream.js:94:10)
    at new DateRollingFileStream (/usr/src/Yunzai-Bot/node_modules/.pnpm/streamroller@3.1.1/node_modules/streamroller/lib/DateRollingFileStream.js:31:5)
    at openTheStream (/usr/src/Yunzai-Bot/node_modules/.pnpm/log4js@6.5.2/node_modules/log4js/lib/appenders/dateFile.js:7:18)
    at appender (/usr/src/Yunzai-Bot/node_modules/.pnpm/log4js@6.5.2/node_modules/log4js/lib/appenders/dateFile.js:42:18)
    at Object.configure (/usr/src/Yunzai-Bot/node_modules/.pnpm/log4js@6.5.2/node_modules/log4js/lib/appenders/dateFile.js:73:10)
    at /usr/src/Yunzai-Bot/node_modules/.pnpm/log4js@6.5.2/node_modules/log4js/lib/appenders/index.js:92:27 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'logs/command.2022-09-28.log'
}
![NNN$@KT9D@K{5U(90@C)(4B](https://user-images.githubusercontent.com/71176604/192667481-cced8911-2cf8-4d24-8d2a-165cedbd3236.png)
这个要咋解决啊，求大佬帮助

**Comment by yuweiliang111** [comment]
root登
