### ISSUE TITLE
#重启失败

### ISSUE THREAD

**Issue by YanQian01** [Le-niao/Yunzai-Bot#69]
失败！
Error code: 1
Error: Command failed: npm restart
[PM2][ERROR] Process or Namespace Yunzai not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yunzai@2.1.2 restart: `pm2 restart Yunzai`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yunzai@2.1.2 restart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-12T00_37_43_567Z-debug.log

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

出错了。请尝试处理错误

**Comment by Le-niao** [comment]
你自己改的名字，只能手动pm2重启了
