### ISSUE TITLE
更新之后重启失败

### ISSUE THREAD

**Issue by loadling** [Le-niao/Yunzai-Bot#707]
开始执行重启，请稍等...
操作失败！
TypeError: Cannot read properties of undefined (reading 'includes')
    at Restart.restart (file:///C:/Users/Administrator/Desktop/Yunzai-Bot-V3/plugins/other/restart.js:64:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai-Bot-V3/lib/plugins/loader.js:248:52)

**Comment by zh8416** [comment]
同样问题，感觉似乎是npm与pnpm的判断出了点问题

**Comment by zh8416** [comment]
> https://github.com/Le-niao/Yunzai-Bot/blob/8e834aed43d158feefeeec2ff539a212e62bad86/plugins/other/restart.js#L64
> 
> node版本是多少？至少要v16
> 
> https://github.com/Le-niao/Yunzai-Bot/blob/8e834aed43d158feefeeec2ff539a212e62bad86/README.md?plain=1#L9



> https://github.com/Le-niao/Yunzai-Bot/blob/8e834aed43d158feefeeec2ff539a212e62bad86/plugins/other/restart.js#L64
> 
> node版本是多少？至少要v16
> 
> https://github.com/Le-niao/Yunzai-Bot/blob/8e834aed43d158feefeeec2ff539a212e62bad86/README.md?plain=1#L9

我是16.14.0，我看ctrlcvs已经修改了restart.js的代码，等乐神批了再更新吧

**Comment by lgyseven** [comment]
同问题，重启报错，有影响到其他插件的更新使用

**Comment by Le-niao** [comment]
更新下就行
