### ISSUE TITLE
关于无法更新的问题

### ISSUE THREAD

**Issue by rehuli0** [Le-niao/Yunzai-Bot#793]
Error: Command failed: git rev-parse --short HEAD
fatal: Needed a single revision

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at update.getcommitId (file:///root/Yunzai-Bot/plugins/other/update.js:151:26)
    at update.runUpdate (file:///root/Yunzai-Bot/plugins/other/update.js:114:35)
    at update (file:///root/Yunzai-Bot/plugins/other/update.js:58:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:248:52)

**Comment by rehuli0** [comment]
给bot发送不返回信息 在终端显示的是上面的代码
