### ISSUE TITLE
重启报错

### ISSUE THREAD

**Issue by touchscale** [Le-niao/Yunzai-Bot#798]
操作失败！
Error: Command failed: pnpm run restart
[PM2][ERROR] Process 0 not found
Process 0 not found
D:\idm\Yunzai-Bot\node_modules\.pnpm\pm2@5.2.0\node_modules\pm2\lib\API.js:1717
        acted.push(proc.pm2_env ? proc.pm2_env.pm_id : proc.pm_id)
                        ^

TypeError: Cannot read properties of undefined (reading 'pm2_env')
    at D:\idm\Yunzai-Bot\node_modules\.pnpm\pm2@5.2.0\node_modules\pm2\lib\API.js:1717:25
    at Array.forEach (<anonymous>)
    at API.speedList (D:\idm\Yunzai-Bot\node_modules\.pnpm\pm2@5.2.0\node_modules\pm2\lib\API.js:1716:18)
    at D:\idm\Yunzai-Bot\node_modules\.pnpm\pm2@5.2.0\node_modules\pm2\lib\binaries\CLI.js:378:11
    at wrapper (D:\idm\Yunzai-Bot\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\once.js:12:16)
    at replenish (D:\idm\Yunzai-Bot\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\eachOfLimit.js:76:25)
    at iterateeCallback (D:\idm\Yunzai-Bot\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\eachOfLimit.js:65:17)
    at D:\idm\Yunzai-Bot\node_modules\.pnpm\async@3.2.4\node_modules\async\internal\onlyOnce.js:12:16
    at D:\idm\Yunzai-Bot\node_modules\.pnpm\pm2@5.2.0\node_modules\pm2\lib\binaries\CLI.js:375:9
    at D:\idm\Yunzai-Bot\node_modules\.pnpm\pm2@5.2.0\node_modules\pm2\lib\API.js:1096:23

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by kikasyou** [comment]
杀后台
npm stop
还原修改
git reset --hard
拉取
git pull
重新安装依赖
npm install pnpm -g
pnpm install -P
运行
node app

**Comment by touchscale** [comment]
> 杀后台 npm stop还原修改 git reset --hard拉取 git pull 重新安装依赖 npm install pnpm -gpnpm install -Prun node app

在前台可以重启成功，变为后台后还是报错
