### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by BZBY** [Le-niao/Yunzai-Bot#802]
QQ配置完成，正在登录
后续修改账号可以运行命令： npm run login

[YzBot][21:23:49.432][MARK] Yunzai-Bot 启动中...
[YzBot][21:23:49.434][MARK] 连接redis....
[YzBot][21:23:49.445][MARK] 连接redis成功
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 847_194_354_847_194_400
    at new NodeError (node:internal/errors:371:5)
    at checkInt (node:internal/buffer:72:11)
    at writeU_Int32BE (node:internal/buffer:802:3)
    at Buffer.writeUInt32BE (node:internal/buffer:815:10)
    at generateImei (C:\paimeng\Yunzai-Bot\node_modules\.pnpm\oicq@2.3.1\node_modules\oicq\lib\core\device.js:9:9)
    at generateShortDevice (C:\paimeng\Yunzai-Bot\node_modules\.pnpm\oicq@2.3.1\node_modules\oicq\lib\core\device.js:54:15)
    at new Client (C:\paimeng\Yunzai-Bot\node_modules\.pnpm\oicq@2.3.1\node_modules\oicq\lib\client.js:56:57)
    at new Yunzai (file:///C:/paimeng/Yunzai-Bot/lib/bot.js:8:5)
    at Function.run (file:///C:/paimeng/Yunzai-Bot/lib/bot.js:15:17)
    at file:///C:/paimeng/Yunzai-Bot/app.js:4:27 {
  code: 'ERR_OUT_OF_RANGE'
}

**Comment by Le-niao** [comment]
qq号问题

**Comment by BZBY** [comment]
可是 我重新下载了云仔 还是这个qq号成功了

**Comment by BZBY** [comment]
> qq号问题

我想问问 怎么重新下载的话怎么绑定到之前的数据库
