### ISSUE TITLE
练度统计 角色列表等命令报错

### ISSUE THREAD

**Issue by am-abudu** [Le-niao/Yunzai-Bot#804]
我的Bot在执行#练度统计或#角色列表时出现了报错
```
    at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52)

    at async roleList (file:///root/Yunzai-Bot/plugins/genshin/apps/role.js:155:16)

    at async Function.get (file:///root/Yunzai-Bot/plugins/genshin/model/roleList.js:19:12)

    at RoleList.getData (file:///root/Yunzai-Bot/plugins/genshin/model/roleList.js:46:15)

    at RoleList.dealData (file:///root/Yunzai-Bot/plugins/genshin/model/roleList.js:156:50)

    at Array.forEach (<anonymous>)

    at file:///root/Yunzai-Bot/plugins/genshin/model/roleList.js:157:46

[23:07:10.673][ERRO] TypeError: Cannot read properties of undefined (reading 'name')

[23:07:10.673][ERRO] [角色查询][roleList]
```
稳定触发，且绑定的Cookie无问题（表现为签到正常）

**Comment by DivinationHW** [comment]
如果你是国际服账号，需要在Hoyolab APP使用一次体力计算器授权一下才可正常使用

**Comment by am-abudu** [comment]
> 如果你是国际服账号，需要在Hoyolab APP使用一次体力计算器授权一下才可正常使用

并非国际服账号 是官服账号

**Comment by am-abudu** [comment]
更新：每次刚开机正常，在五到十分钟后出现错误
