### ISSUE TITLE
体力获取bug

### ISSUE THREAD

**Issue by x0rz4** [Le-niao/Yunzai-Bot#81]
```
/root/Yn/Yunzai-Bot-master/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/Yn/Yunzai-Bot-master/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:237:20)
    at Interface.<anonymous> (/root/Yn/Yunzai-Bot-master/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:227:68)
    at Interface.emit (node:events:538:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-04-18T00:23:48.452] [ERROR] error - puppeteer 启动失败

```

**Comment by Le-niao** [comment]
不是bug是你没装依赖 `libatk-bridge-2.0.so.0`
