### ISSUE TITLE
载入插件错误：enka(已经安装过，使用过之间的解决方案)

### ISSUE THREAD

**Issue by ANh0r** [Le-niao/Yunzai-Bot#852]
pi@1.5.2/node_modules/enka-network-api/src/models/assets/TextAssets.js:26
        lang ??= this.enka.options.defaultLanguage;
             ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/cassiopeia/College/Postgraduate Term 1/genshin-bot/Yunzai-Bot/node_modules/.pnpm/enka-network-api@1.5.2/node_modules/enka-network-api/src/models/artifact/ArtifactData.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[YzBot][15:46:19.852][ERRO] /Users/cassiopeia/College/Postgraduate Term 1/genshin-bot/Yunzai-Bot/node_modules/.pnpm/enka-network-api@1.5.2/node_modules/enka-network-api/src/models/assets/TextAssets.js:26
        lang ??= this.enka.options.defaultLanguage;
             ^^^

已经用过之前的例子，安装过enka
但是出现了这个问题 请问怎么解决？

**Comment by ANh0r** [comment]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/45546300/200506415-334173b3-92e4-4702-8964-cb2fcaa34e2d.png">
更改源码从"??="改为“+=”

**Comment by Crd39** [comment]
![图片](https://user-images.githubusercontent.com/43436657/200562011-41437f58-b3b0-4495-b71e-f8c3b25f9bf1.png)
改成這個，我懷疑是js版本問題

**Comment by ANh0r** [comment]
> ![图片](https://user-images.githubusercontent.com/43436657/200562011-41437f58-b3b0-4495-b71e-f8c3b25f9bf1.png) 改成這個，我懷疑是js版本問題

我本来就是??= 他会报错……

**Comment by Crd39** [comment]
> > ![图片](https://user-images.githubusercontent.com/43436657/200562011-41437f58-b3b0-4495-b71e-f8c3b25f9bf1.png) 改成這個，我懷疑是js版本問題
> 
> 我本来就是??= 他会报错……

改成我截图里的那样就能跑了

**Comment by ANh0r** [comment]
> > > ![图片](https://user-images.githubusercontent.com/43436657/200562011-41437f58-b3b0-4495-b71e-f8c3b25f9bf1.png) 改成這個，我懷疑是js版本問題
> > 
> > 
> > 我本来就是??= 他会报错……
> 
> 改成我截图里的那样就能跑了 就把??= 改成 if ( !lang) lang

疑惑 我改成的是 += 也能跑 具体原因是啥呢

**Comment by Lo1iame** [comment]
遇到过同款问题，我是因为node版本低了，我把14升到16之后重新装了依赖就好了
