### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by 1011382654** [Le-niao/Yunzai-Bot#854]
报错命令是#刻晴攻略，结尾如果加数字如：刻晴攻略1-4就正常 

TypeError: Cannot read properties of undefined (reading 'forEach')
    at strategy.getImg (file:///www/wwwroot/Yunzai-Bot/plugins/genshin/apps/strategy.js:138:31)
    at strategy (file:///www/wwwroot/Yunzai-Bot/plugins/genshin/apps/strategy.js:114:20)
    at PluginsLoader.deal (file:///www/wwwroot/Yunzai-Bot/lib/plugins/loader.js:247:55)

**Comment by 1011382654** [comment]
额，不知道为什么mys.set.yaml的默认攻略来源是NaN导致的报错
