### ISSUE TITLE
一直正常使用重启后突然报错

### ISSUE THREAD

**Issue by rehuli0** [Le-niao/Yunzai-Bot#983]
![QQ截图20221204120019](https://user-images.githubusercontent.com/78489908/205473784-1cc27883-c64f-4d2f-ba2e-339bfba90912.png)

**Comment by rehuli0** [comment]
node app
/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:69
                this.errors.push(new errors.YAMLParseError(pos, code, message));
                                 ^

YAMLParseError: Nested mappings are not allowed in compact mappings at line 1, column 12:

/bin/bash: line 1: Z: command not found
           ^

    at Composer.onError (/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:69:34)
    at Object.resolveBlockMap (/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/resolve-block-map.js:72:21)
    at Object.composeCollection (/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/compose-collection.js:13:36)
    at Object.composeNode (/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.composeDoc (/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/compose-doc.js:32:23)
    at Composer.next (/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:149:40)
    at next (<anonymous>)
    at Composer.compose (/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:131:25)
    at compose.next (<anonymous>)
    at parseDocument (/root/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/public-api.js:45:16) {
  code: 'BLOCK_AS_IMPLICIT_KEY',
  pos: [ 11, 12 ],
  linePos: [ { line: 1, col: 12 }, { line: 1, col: 13 } ]
}

Node.js v19.0.1
